version: "3.9"
volumes:
  db-store:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    container_name: "backend_laravel"
    volumes:
      - type: bind
        source: ./src
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    # 컨테이너 내 환경변수 설정, laravel의 경우 config폴더 내에서도 지정 가능.
    # environment:
      # - APP_DEBUG=${APP_DEBUG:-true}
      # - APP_KEY=${APP_KEY:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
      # - APP_ENV=${APP_ENV:-local}
      # - APP_URL=${APP_URL:-http://localhost}
      # - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      # - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      # - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      # - DB_HOST=${DB_HOST:-postgres}
      # - DB_PORT=${DB_PORT:-9202}
      # - DB_DATABASE=${DB_DATABASE:-test-db}
      # - DB_USERNAME=${DB_USERNAME:-test-db-user}
      # - DB_PASSWORD=${DB_PASSWORD:-}

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    container_name: "server_nginx"
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /workspace

  postgres:
    image: postgres:11.8
    container_name: "db_postgresql"
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - "9202:9202"
    command: -p 9202
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'test-db-user'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'test-db'

  graphql:
    image: hasura/graphql-engine:v2.10.1
    # console port는 8080아니면 인식 안되나?
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://test-db-user:@postgres:9202/test-db
      PG_DATABASE_URL: postgres://test-db-user:@postgres:9202/test-db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: hasurapass